games:
- name: Age of Empires II
  type: game
  base_path: Installers/Age of Empires II
  version: '1.0'
  install_msi: game/Age of Empires II.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: game/Age of Empires II.msi
- name: Battlefield 1942
  type: game
  base_path: Installers/Battlefield 1942
  version: '1.0'
  install_msi: game/Battlefield 1942.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: game/Battlefield 1942.msi
  - path: game/Data1.cab
  - path: game/Data11.cab
  - path: game/Data12.cab
- name: Battlefield 3
  type: game
  base_path: Installers/Battlefield 3
  version: 1.00.0000
  install_msi: game/Battlefield 3.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: game/Battlefield 3.msi
  - path: game/Data1.cab
  - path: game/Data11.cab
  - path: game/Data110.cab
  - path: game/Data111.cab
  - path: game/Data112.cab
  - path: game/Data113.cab
  - path: game/Data114.cab
  - path: game/Data115.cab
  - path: game/Data116.cab
  - path: game/Data117.cab
  - path: game/Data118.cab
  - path: game/Data119.cab
  - path: game/Data12.cab
  - path: game/Data120.cab
  - path: game/Data121.cab
  - path: game/Data122.cab
  - path: game/Data123.cab
  - path: game/Data124.cab
  - path: game/Data125.cab
  - path: game/Data126.cab
  - path: game/Data127.cab
  - path: game/Data128.cab
  - path: game/Data129.cab
  - path: game/Data13.cab
  - path: game/Data130.cab
  - path: game/Data131.cab
  - path: game/Data14.cab
  - path: game/Data15.cab
  - path: game/Data16.cab
  - path: game/Data17.cab
  - path: game/Data18.cab
  - path: game/Data19.cab
- name: Battlefield Bad Company 2
  type: game
  base_path: Installers/Battlefield Bad Company 2
  version: 1.00.0000
  install_msi: Game/Battlefield Bad Company 2.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Battlefield Bad Company 2.msi
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
  - path: Game/Data13.cab
  - path: Game/Data14.cab
  - path: Game/Data15.cab
  - path: Game/Data16.cab
  - path: Game/Data17.cab
  - path: Game/Data18.cab
- name: Battlefield Bad Company 2 Server
  type: server
  base_path: Installers/Battlefield Bad Company 2
  version: 1.00.0000
  install_msi: Server/Battlefield Bad Company 2 Server.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Server/Battlefield Bad Company 2 Server.msi
- name: Battlefield Multi Server
  type: server
  base_path: Installers/Battlefield Multi Server
  version: 1.00.0000
  install_msi: server/Battlefield Multi Server.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: server/Battlefield Multi Server.msi
  - path: server/Data1.cab
  - path: server/Data11.cab
  - path: server/Data12.cab
  - path: server/Data13.cab
  - path: server/Data14.cab
  - path: server/Data15.cab
- name: Call Of Duty
  type: game
  base_path: Installers/Call Of Duty
  version: 1.00.0000
  install_msi: Game/Call Of Duty.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Call Of Duty.msi
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
- name: Call Of Duty 4
  type: game
  base_path: Installers/Call Of Duty 4
  version: 1.00.0000
  install_msi: Game/Call Of Duty 4.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Call Of Duty 4.msi
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
  - path: Game/Data13.cab
  - path: Game/Data14.cab
  - path: Game/Data15.cab
- name: Chivalry Medieval Warfare
  type: game
  base_path: Installers/Chivalry Medieval Warfare
  version: 1.00.0000
  install_msi: Game/Chivalry Medieval Warfare.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Chivalry Medieval Warfare.msi
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
  - path: Game/Data13.cab
  - path: Game/Data14.cab
  - path: Game/Data15.cab
  - path: Game/Data16.cab
  - path: Game/Data17.cab
- name: Chivalry Medieval Warfare Server
  type: server
  base_path: Installers/Chivalry Medieval Warfare
  version: 1.00.0000
  install_msi: Server/Chivalry Medieval Warfare Server.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Server/Chivalry Medieval Warfare Server.msi
  - path: Server/Data1.cab
- name: Counter-Strike Global Offensive
  type: game
  base_path: Installers/Counter-Strike Global Offensive
  version: 1.00.0000
  install_msi: Game/Counter-Strike Global Offensive.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Counter-Strike Global Offensive.msi
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
  - path: Game/Data13.cab
  - path: Game/Data14.cab
- name: Duck Game
  type: game
  base_path: Installers/Duck Game
  version: 1.00.0000
  install_msi: game/Duck Game.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: game/Data1.cab
  - path: game/Duck Game.msi
- name: Flatout 2
  type: game
  base_path: Installers/Flatout 2
  version: 1.00.0000
  install_msi: Game/Flatout 2.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
  - path: Game/Flatout 2.msi
- name: Garrys Mod
  type: game
  base_path: Installers/Garrys Mod
  version: 1.00.0000
  install_msi: Game/Garrys Mod.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
  - path: Game/Data13.cab
  - path: Game/Garrys Mod.msi
- name: Grand Theft Auto IV
  type: game
  base_path: Installers/Grand Theft Auto IV
  version: 1.00.0000
  install_msi: game/Grand Theft Auto IV.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: game/Data1.cab
  - path: game/Data11.cab
  - path: game/Data110.cab
  - path: game/Data111.cab
  - path: game/Data112.cab
  - path: game/Data113.cab
  - path: game/Data114.cab
  - path: game/Data12.cab
  - path: game/Data13.cab
  - path: game/Data14.cab
  - path: game/Data15.cab
  - path: game/Data16.cab
  - path: game/Data17.cab
  - path: game/Data18.cab
  - path: game/Data19.cab
  - path: game/Grand Theft Auto IV.msi
- name: Killing Floor
  type: game
  base_path: Installers/Killing Floor
  version: 1.00.0000
  install_msi: Game/Killing Floor.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
  - path: Game/Killing Floor.msi
- name: Left 4 Dead 2
  type: game
  base_path: Installers/Left 4 Dead 2
  version: 1.00.0000
  install_msi: Game/Left 4 Dead 2.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
  - path: Game/Data13.cab
  - path: Game/Data14.cab
  - path: Game/Data15.cab
  - path: Game/Data16.cab
  - path: Game/Data17.cab
  - path: Game/Data18.cab
  - path: Game/Data19.cab
  - path: Game/Left 4 Dead 2.msi
- name: Need for Speed SHIFT
  type: game
  base_path: Installers/Need for Speed SHIFT
  version: 1.00.0000
  install_msi: Game/Need for Speed SHIFT.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
  - path: Game/Data13.cab
  - path: Game/Data14.cab
  - path: Game/Data15.cab
  - path: Game/Need for Speed SHIFT.msi
- name: Red Alert 3
  type: game
  base_path: Installers/Red Alert 3
  version: 1.00.0000
  install_msi: Game/Red Alert 3.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
  - path: Game/Data13.cab
  - path: Game/Data14.cab
  - path: Game/Data15.cab
  - path: Game/Data16.cab
  - path: Game/Red Alert 3.msi
- name: StarCraft II
  type: game
  base_path: Installers/StarCraft II
  version: 1.00.0000
  install_msi: game/StarCraft II.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: game/StarCraft II.msi
- name: Team Fortress 2
  type: game
  base_path: Installers/Team Fortress 2
  version: 1.00.0000
  install_msi: Game/Team Fortress 2.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
  - path: Game/Data13.cab
  - path: Game/Data14.cab
  - path: Game/Data15.cab
  - path: Game/Data16.cab
  - path: Game/Data17.cab
  - path: Game/Team Fortress 2.msi
- name: Tom Clancys Rainbow Six Siege
  type: game
  base_path: Installers/Tom Clancys Rainbow Six Siege
  version: '1.0'
  install_msi: game/Tom Clancys Rainbow Six Siege.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: game/Data1.cab
  - path: game/Data11.cab
  - path: game/Data110.cab
  - path: game/Data111.cab
  - path: game/Data112.cab
  - path: game/Data113.cab
  - path: game/Data12.cab
  - path: game/Data13.cab
  - path: game/Data14.cab
  - path: game/Data15.cab
  - path: game/Data16.cab
  - path: game/Data17.cab
  - path: game/Data18.cab
  - path: game/Data19.cab
  - path: game/Tom Clancys Rainbow Six Siege.msi
- name: Unreal Tournament 3
  type: game
  base_path: Installers/Unreal Tournament 3
  version: 1.00.0000
  install_msi: Game/Unreal Tournament 3.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Data12.cab
  - path: Game/Data13.cab
  - path: Game/Data14.cab
  - path: Game/Data15.cab
  - path: Game/Data16.cab
  - path: Game/Data17.cab
  - path: Game/Data18.cab
  - path: Game/Unreal Tournament 3.msi
- name: Warcraft III
  type: game
  base_path: Installers/Warcraft III
  version: 1.00.0000
  install_msi: Game/Warcraft III.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: Game/Data1.cab
  - path: Game/Data11.cab
  - path: Game/Warcraft III.msi
- name: Wreckfest
  type: game
  base_path: Installers/Wreckfest
  version: 1.00.0000
  install_msi: game/Wreckfest.msi
  supports_player_name: false
  prerequisites: []
  files:
  - path: game/Data1.cab
  - path: game/Data11.cab
  - path: game/Data110.cab
  - path: game/Data111.cab
  - path: game/Data112.cab
  - path: game/Data113.cab
  - path: game/Data114.cab
  - path: game/Data115.cab
  - path: game/Data116.cab
  - path: game/Data117.cab
  - path: game/Data118.cab
  - path: game/Data119.cab
  - path: game/Data12.cab
  - path: game/Data120.cab
  - path: game/Data121.cab
  - path: game/Data122.cab
  - path: game/Data123.cab
  - path: game/Data124.cab
  - path: game/Data125.cab
  - path: game/Data126.cab
  - path: game/Data127.cab
  - path: game/Data128.cab
  - path: game/Data129.cab
  - path: game/Data13.cab
  - path: game/Data14.cab
  - path: game/Data15.cab
  - path: game/Data16.cab
  - path: game/Data17.cab
  - path: game/Data18.cab
  - path: game/Data19.cab
  - path: game/Wreckfest.msi
