games:
  - name: "Age of Empires II"
    install_msi: "Installers/Age of Empires II/game/Age of Empires II.msi"
    supports_player_name: false
    prerequisites: []

  - name: "Battlefield 1942"
    install_msi: "Installers/Battlefield 1942/game/Battlefield 1942.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Battlefield 3"
    install_msi: "Installers/Battlefield 3/game/Battlefield 3.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Battlefield Bad Company 2"
    install_msi: "Installers/Battlefield Bad Company 2/game/Battlefield Bad Company 2.msi"
    supports_player_name: true
    requires_server_ip: true
    prerequisites: []

  - name: "Call Of Duty"
    install_msi: "Installers/Call Of Duty/game/Call Of Duty.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Call Of Duty 4"
    install_msi: "Installers/Call Of Duty 4/game/Call Of Duty 4.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Chivalry Medieval Warfare"
    install_msi: "Installers/Chivalry Medieval Warfare/game/Chivalry Medieval Warfare.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Counter-Strike Global Offensive"
    install_msi: "Installers/Counter-Strike Global Offensive/game/Counter-Strike Global Offensive.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Duck Game"
    install_msi: "Installers/Duck Game/game/Duck Game.msi"
    supports_player_name: false
    prerequisites: []

  - name: "Flatout 2"
    install_msi: "Installers/Flatout 2/game/Flatout 2.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Garrys Mod"
    install_msi: "Installers/Garrys Mod/game/Garrys Mod.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Grand Theft Auto IV"
    install_msi: "Installers/Grand Theft Auto IV/game/Grand Theft Auto IV.msi"
    supports_player_name: true

  - name: "Killing Floor"
    install_msi: "Installers/Killing Floor/game/Killing Floor.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Left 4 Dead 2"
    install_msi: "Installers/Left 4 Dead 2/game/Left 4 Dead 2.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Need for Speed SHIFT"
    install_msi: "Installers/Need for Speed SHIFT/game/Need for Speed SHIFT.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Red Alert 3"
    install_msi: "Installers/Red Alert 3/game/Red Alert 3.msi"
    supports_player_name: true
    prerequisites: []

  - name: "StarCraft II"
    install_msi: "Installers/StarCraft II/game/StarCraft II.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Team Fortress 2"
    install_msi: "Installers/Team Fortress 2/game/Team Fortress 2.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Tom Clancys Rainbow Six Siege"
    install_msi: "Installers/Tom Clancys Rainbow Six Siege/game/Tom Clancys Rainbow Six Siege.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Unreal Tournament 3"
    install_msi: "Installers/Unreal Tournament 3/game/Unreal Tournament 3.msi"
    supports_player_name: true
    prerequisites: []

  - name: "Warcraft III"
    install_msi: "Installers/Warcraft III/game/Warcraft III.msi"
    supports_player_name: false
    prerequisites: []

  - name: "Wreckfest"
    install_msi: "Installers/Wreckfest/game/Wreckfest.msi"
    supports_player_name: true
    prerequisites: []
