games:
- name: Battlefield 4
  type: game
  installer_type: inno_setup
  base_path: Installers/Battlefield 4
  version: '1.0'
  install_exe: game/Battlefield 4.exe
  supports_player_name: false
  prerequisites: []
  files:
  - path: game/Battlefield 4-1.bin
  - path: game/Battlefield 4.exe
